services:
    oai-cu:
        image: oai-gnb:cu_mirror
        container_name: rfsim5g-oai-cu
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        command: >
            bash -c "
                iptables -I OUTPUT -p udp --dport 2152 -j NFQUEUE --queue-num 1
                iptables -I INPUT -p udp --dport 2152 -j NFQUEUE --queue-num 1
                arp -s 192.168.73.160 02:42:c0:a8:49:a0 -i eth1
                iptables -t mangle -A PREROUTING -i eth0 -j TEE --gateway 192.168.73.160
                iptables -t mangle -A POSTROUTING -o eth0 -j TEE --gateway 192.168.73.160
                iptables -t mangle -L -v -n
                python3 /opt/oai-gnb/cu-agent/script-fw/multi_threat_fw.py &
                exec /opt/oai-gnb/bin/entrypoint.sh /opt/oai-gnb/bin/nr-softmodem
            "
        environment: 
            USE_ADDITIONAL_OPTIONS: --rfsimulator.options chanmod
                                    --telnetsrv --telnetsrv.listenaddr 192.168.70.150
                                    --telnetsrv.shrmod ci
            ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.70.150
            cu_net:
                ipv4_address: 192.168.73.150
        volumes:
            - ./ran-conf/rfsim.cu.conf:/opt/oai-gnb/etc/gnb.conf
            - ./cu-agent:/opt/oai-gnb/cu-agent
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-du:
        image: jamsier/oai-gnb:CRW25
        container_name: rfsim5g-oai-du
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim
                                    --telnetsrv --telnetsrv.listenaddr 192.168.70.171
                                    --telnetsrv.shrmod ci
            ASAN_OPTIONS: detect_leaks=0:detect_odr_violation=0s
        depends_on:
            - oai-cu
        networks:
            public_net:
                ipv4_address: 192.168.70.171
        volumes:
            - ./ran-conf/rfsim.du.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue:
        image: jamsier/oai-nr-ue:CRW25
        container_name: rfsim5g-oai-nr-ue
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -C 3619200000 -r 106 --numerology 1 --rfsimulator.serveraddr 192.168.70.171
            ASAN_OPTIONS: detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.70.181
        devices:
            - /dev/net/tun:/dev/net/tun
        volumes:
            - ./ran-conf/nrue.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ./lowRateDoS:/opt/oai-nr-ue/etc/lowRateDoS
            - ./normalUser:/opt/oai-nr-ue/etc/normalUser
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue2:
        image: jamsier/oai-nr-ue:CRW25
        container_name: rfsim5g-oai-nr-ue2
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -C 3619200000 -r 106 --numerology 1 --rfsimulator.serveraddr 192.168.70.171 --uicc0.imsi 001010000000002
            ASAN_OPTIONS: detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.70.182
        devices:
            - /dev/net/tun:/dev/net/tun
        volumes:
            - ./ran-conf/nrue.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ./normalUser:/opt/oai-nr-ue/etc/normalUser
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
    oai-nr-ue3:
        image: jamsier/oai-nr-ue:CRW25
        container_name: rfsim5g-oai-nr-ue3
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: -E --rfsim -C 3619200000 -r 106 --numerology 1 --rfsimulator.serveraddr 192.168.70.171 --uicc0.imsi 001010000000003
            ASAN_OPTIONS: detect_odr_violation=0
        networks:
            public_net:
                ipv4_address: 192.168.70.183
        devices:
            - /dev/net/tun:/dev/net/tun
        volumes:
            - ./ran-conf/nrue.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - ./normalUser:/opt/oai-nr-ue/etc/normalUser
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    traffic-capture:
        image: jamsier/traffic-capture:CRW25
        container_name: traffic-capture
        # command: bash -c "ip link set dev eth0 promisc on && ip addr flush dev eth0 && sleep infinity"
        command: bash -c "ip link set dev eth0 promisc on && ip addr flush dev eth0 && ./cu-agent/script/auto-run.sh"
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        networks:
            cu_net:
                ipv4_address: 192.168.73.160
        privileged: true
        volumes:
            - ./cu-agent:/code/cu-agent
    e2-agent:
        image: jamsier/flexric:kpm
        command: bash -c "./tmp/cu-agent/script/get_malicious_ip.sh & stdbuf -o0 /usr/local/flexric/emulator/agent/emu_agent_gnb"
        container_name: e2-agent
        networks:
            cu_net:
                ipv4_address: 192.168.73.161
            e2_net:
                ipv4_address: 192.168.72.161
        volumes:
            - ../flexric.conf:/usr/local/etc/flexric/flexric.conf
            - ./cu-agent:/tmp/cu-agent
            - ./cu-agent/pcap/flow-data:/tmp/flow_data
            - ./near-rt-ric/measurements_data:/tmp/measurements_data
            - ./near-rt-ric/malicious_ip.json:/tmp/malicious_ip.json

networks:
    public_net:
        external: true
        name: oai-cn5g-public-net
    e2_net:
        external: true
        name: oai-e2-net

    cu_net:
        driver: bridge
        name: oai-cu-net
        ipam:
            config:
                - subnet: 192.168.73.0/24
        driver_opts:
            com.docker.network.bridge.name: "cu"

